import React, { useEffect } from 'react';
import './Legal.css';
import content from './privacy-policy.content.html';

export const PRIVACY_POLICY_TITLE = 'Privacy Policy · Signal-23';

/**
 * SPA fallback for /legal/privacy. Production serves the static, script-free
 * build/legal/privacy/index.html generated by scripts/legal-pages.js from the
 * same content file, so the policy text has exactly one source.
 */
export const PrivacyPolicy: React.FC = () => {
  useEffect(() => {
    const previousTitle = document.title;
    document.title = PRIVACY_POLICY_TITLE;
    return () => {
      document.title = previousTitle;
    };
  }, []);

  // Our own static policy markup, not user input.
  return <main className="legal-page" dangerouslySetInnerHTML={{ __html: content }} />;
};
